name 'linking-commerce-api'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures linking-commerce-api'
long_description 'Installs/Configures linking-commerce-api'
version '0.1.0'

depends 'apt'
depends 'sudo'
depends 'ruby-ng'
depends 'timezone-ii'
