development:
    certificate: "apns/development_com.xpeppers.TrentinoDaVivere.pem"

test:
    certificate: "apns/development_com.xpeppers.TrentinoDaVivere.pem"

staging:
    certificate: "apns/development_com.xpeppers.TrentinoDaVivere.pem"

production:
    certificate: "apns/production_com.xpeppers.TrentinoDaVivere.pem"
